---
- name: reload systemd daemon
  sudo: yes
  command: systemctl daemon-reload
  tags:
    - logstash

- name: enable and start logstash
  sudo: yes
  service:
    enabled: yes
    name: logstash
    state: started
  tags:
    - logstash

- name: restart logstash
  sudo: yes
  service:
    name: logstash
    state: restarted
  tags:
    - logstash
