---
- name: Install Java package
  sudo: true
  yum:
    name: java-1.8.0-openjdk
    state: present
  tags:
    - spark

- name: Create Spark directory
  sudo: true
  file:
    path: "{{ spark_install_dir }}"
    state: directory
  tags:
    - spark

- name: Download Spark binaries
  sudo: true 
  get_url: 
    url: "http://mirror.ox.ac.uk/sites/rsync.apache.org/spark/spark-{{ item }}/spark-{{ item }}-bin-hadoop{{ item < '1.3.1' and '2.4' or '2.6' }}.tgz"
    dest: "{{ spark_install_dir }}/spark-{{ item }}-bin-hadoop{{ item < '1.3.1' and '2.4' or '2.6' }}.tgz"
  with_items: spark_versions
  tags:
    - spark 

- name: Check whether hdfs user exists or not
  shell: "getent passwd hdfs >/dev/null 2>&1 && echo 'True' || echo 'False'"
  register: hdfs_exists

- name: Create Spark user home directory on HDFS
  run_once: true
  sudo_user: hdfs
  sudo: true
  shell: source /etc/profile.d/hadoop.sh; if ! hdfs dfs -test -d /user/{{ spark_user }}; then hdfs dfs -mkdir -p /user/{{ spark_user }}; fi; hdfs dfs -chown {{ spark_user }} /user/{{ spark_user }}
  when: hdfs_exists.stdout == 'True'
  tags:
    - spark

- include: client.yml
